baseURL = "https://nztakahe.github.io/"
languageCode = "en-us"
title = "Dwarfstar sysops notes"
theme = "hugo-theme-nix"
disableHugoGeneratorInject = true

#https://github.com/hnarayanan/harishnarayanan.org/blob/master/config.yml
#pluralizeListTitles: false
#staticDir: assets
#taxonomies: false

[params]
  GithubID = "nztakahe"
#  BitbucketID = "your_bitbucket_id"
#  TwitterID = "your_twitter"
#  CodepenID = "your_codepen"
  LinkedInID = "michael-menzies"
#  FacebookID = "your_facebook"
  Name = "Michael Menzies"
  HeaderUsername = "michael"
  HeaderHostname = "dwarfstar"
  Email = "noreply@dwarfstar.co.nz"
  About = "A System/Network Engineer that dabbles in bits and pieces.  This is a collection of random ramblings while learning new stuff."
  ProfilePicture = "/looksbetter.png"
  GoogleAnalytics = "UA-113773767-1"
  SlackURL = "https://dwarf-star.slack.com/"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

  [[menu.header]]
    name = "links"
    weight = 2
    url = "/links"

  [[menu.header]]
    name = "about"
    weight = 10
    url = "/about"

